# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3126505df548eee87fe0796f40e5ee18c68f0b3670cb1031b2c6e68a8e3c801b4bb8638eb8bce092d7d48bba1c6926d1cdd6d7cd5deaf02a339915abb324b9

test:
  secret_key_base: d0f6b015fbd88f9396134a07babd2ad1e2eec813682284256a93fa7def4a8b657cfa58eaabfb9b86a7b8e33e9958f9acd65c2eb2e7c4bd8242480534a6ad0b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
